name: matrix
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest]
        include:
          - node-version: 14
            os: ubuntu-latest
          - node-version: 14
            os: windows-latest
        exclude:
          - node-version: 20
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: node modules
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: install app
        run: npm ci
      - name: build the app
        run: npm run build
