name: matrix
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: get the code
        uses: actions/checkout@v4
      - name: node modules
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
      - name: install app
        run: npm ci
      - name: build the app
        run: npm run build
