name: Execution Flow
on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "**/.github/workflows"
  pull_request:
    branches:
      - main
    types: [closed]
    paths-ignore:
      - "**/.github/workflows"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the files
        uses: actions/checkout@v5
      - name: install dependecies
        run: npm ci
      - name: Run Test
        run: npm run test
