name: reusable workflows
on:
  workflow_call:
    inputs:
      artifact-name:
        description: artifacts name
        required: false
        default: dist
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download the Artifacts
        uses: actions/download-artifact@v4
      - name: list the files
        run: ls
      - name: Deploy the project
        run: echo "Deploying"
